### ISSUE TITLE
styles.css too generic.

### ISSUE THREAD

**Issue by danmarsden** [maysaraadmin/moodle-block_quranplayer#2]
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by maysaraadmin** [comment]
Thank you for pointing out the potential issue with the CSS specificity in the `styles.css` file. You're absolutely correct that using generic class names like `.alert`, `.alert-error`, and `.alert-warning` could lead to clashes with core Moodle styles or other plugins. 

To address this, I will update the CSS to make it more specific by leveraging the `path-block-quranplayer` class that Moodle adds to the body tag. This will ensure that the styles are scoped specifically to the Quran Player block and won't interfere with other parts of Moodle or other plugins.

Here’s the updated CSS:

```css
/* Quran Player block styles */
.path-block-quranplayer #quranplayer {
    width: 100%;
    margin-top: 10px;
}

.path-block-quranplayer #quranplayer-select {
    width: 100%;
    margin-bottom: 10px;
    padding: 8px;
    border-radius: 4px;
    border: 1px solid #ccc;
    background-color: #fff;
    font-size: 16px;
}

.path-block-quranplayer #quran-text {
    margin-top: 20px;
    padding: 15px;
    background-color: #f9f9f9;
    border: 1px solid #ddd;
    border-radius: 4px;
}

.path-block-quranplayer #quran-text pre {
    white-space: pre-wrap;
    word-wrap: break-word;
    font-family: 'Amiri', serif;
    font-size: 18px;
    line-height: 1.6;
    margin: 0;
    color: #333;
}

.path-block-quranplayer .quranplayer-alert {
    padding: 10px;
    margin-bottom: 10px;
    border-radius: 4px;
}

.path-block-quranplayer .quranplayer-alert-error {
    background-color: #f8d7da;
    border-color: #f5c6cb;
    color: #721c24;
}

.path-block-quranplayer .quranplayer-alert-warning {
    background-color: #fff3cd;
    border-color: #ffeeba;
    color: #856404;
}

@media (max-width: 768px) {
    .path-block-quranplayer #quranplayer-select {
        font-size: 14px;
    }

    .path-block-quranplayer #quran-text pre {
        font-size: 16px;
    }
}
```

### Changes Made:
1. **Renamed `.alert` to `.quranplayer-alert`**: This ensures that the alert styles are specific to the Quran Player block and won't clash with other alert styles in Moodle.
2. **Renamed `.alert-error` to `.quranplayer-alert-error`**: Similarly, this change ensures that error alerts are specific to the Quran Player block.
3. **Renamed `.alert-warning` to `.quranplayer-alert-warning`**: This ensures that warning alerts are specific to the Quran Player block.

By prefixing these classes with `quranplayer-`, we ensure that they are unique to the Quran Player block and won't interfere with other parts of Moodle or other plugins.

Thank you again for your feedback! If you have any further suggestions or concerns, please let me know.
