### ISSUE TITLE
consider adding github actions support.

### ISSUE THREAD

**Issue by danmarsden** [maysaraadmin/moodle-block_quranplayer#5]
Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by maysaraadmin** [comment]
Thank you for the suggestion! I've gone ahead and created a `ci.yml` file based on the provided template and placed it in the `.github/workflows` directory of my project. This will enable GitHub Actions to run the Moodle Plugin CI tests on every commit to the `main` branch and for pull requests targeting `main`.

Here's a summary of what I did:

1. Created the `.github/workflows` directory 
2. Added the `ci.yml` file with the following content:

```yaml
name: Moodle Plugin CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.18'  # Adjust to the required PHP version
          extensions: mbstring, xml, curl, zip, intl, json, gd, pdo_mysql, mysqli, soap, iconv
          coverage: none

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to the required Node.js version

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      - name: Install npm dependencies
        run: |
          npm install

      - name: Run Moodle Plugin CI
        uses: moodlehq/moodle-plugin-ci@master
        with:
          repo: ${{ github.repository }}
          plugin: block_quranplayer
          moodle-branch: MOODLE_311_STABLE  # Adjust to the correct Moodle branch
```

This configuration will ensure that the Moodle Plugin CI tests are run automatically on every commit, helping to catch any issues early and ensure that the plugin continues to follow Moodle's guidelines.

I appreciate the guidance, and I'm looking forward to seeing the test results in action! If there are any further adjustments or improvements needed, please let me know.
